version: "3.8"

services:
  api:
    container_name: nestjs_simplified_pix_api
    build: .
    restart: always
    tty: true
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      make start:prod
    networks:
      - nestjs_simplified_pix_network

networks:
  nestjs_simplified_pix_network:
    driver: bridge