version: "3.8"

services:
  api:
    container_name: ndix_api
    build: .
    depends_on:
      - database
    restart: always
    tty: true
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      make start-prod
    networks:
      - ndix_network
  database:
    image: bitnami/postgresql:15.6.0
    container_name: ndix_database
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ndix_network

networks:
  ndix_network:
    driver: bridge