name: Generate Coverage PR

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  generate-coverage-pr:
    strategy:
      matrix:
        node-version: [20.6.1]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate coverage report
        run: yarn test --coverage
          
      - name: Setup coverage files
        run: |
          mkdir -p tests/coverage
          mv tests/coverage/lcov-report/* tests/coverage/
          mv tests/coverage/lcov.info tests/coverage/
          rm -rf tests/coverage/lcov-report
          git add tests/coverage

      - name: Create Pull Request
        id: "open-pr"
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: Add test coverage report"
          title: "test(coverage): update"
          body: "This PR adds the test coverage report generated by the GitHub Actions workflow."
          branch: "test/actions/coverage-report"
          base: "Coverage-Report"
          labels: "automated"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}

      - name: "Delete PR Branch"
        run: git push origin --delete test/actions/coverage-report
