name: Generate Coverage PR

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  generate-coverage-pr:
    strategy:
      matrix:
        node-version: [20.6.1]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate coverage report
        run: yarn test --coverage

      - name: Prepare coverage files
        run: |
          mkdir -p temp-coverage
          mv test/coverage/lcov-report/* temp-coverage/ || true
          mv test/coverage/lcov.info temp-coverage/ || true
          git rm -rf $(ls | grep -v '^temp-coverage$' || echo "no-files-to-remove") || true
          mv temp-coverage/* .
          rmdir temp-coverage || true
          git add .
          git commit -m "feat: Add test coverage report" || echo "No changes to commit"

      - name: Create Pull Request
        id: "open-pr"
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: Add test coverage report"
          title: "test(coverage): update"
          body: "This PR adds the test coverage report generated by the GitHub Actions workflow."
          branch: "test/actions/coverage-report"
          base: "Coverage-Report"
          labels: "automated"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}
      
      - name: Lock Pull Request
        uses: sudo-bot/action-pull-request-lock@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.open-pr.outputs.pull-request-number }}
          lock-reason: resolved

      - name: "Delete PR Branch"
        run: git push origin --delete test/actions/coverage-report
