# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
    paths: "**/*.ts"
  pull_request:
    branches: [master]
    paths: "**/*.ts"


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install workspace dependencies
        run: yarn install --immutable

      - name: Install api dependencies
        run: cd apps/api && yarn install --immutable

      - name: Install mobile dependencies
        run: cd apps/mobile && yarn install --immutable
